name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run action
      uses: Akshay090/github_action@master
      with:
        path: ${{ secrets.test }}
